import './globals.css'
import { Rubik } from 'next/font/google'

// components 
import Navbar from './components/navbar'
import Provider from './components/provider'


const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <main> 
      <Provider> 
      
      <body className={rubik.className}>
        <Navbar />
        {children}</body>
       
        </Provider>  </main>
    </html>
  )
}
